export {
  assessConfidence,
  assessGoalImpact,
  assessRisk,
  buildTimeline,
  calculateAvailableToSpend,
  calculateDailySafeToSpend,
  confidence,
  createDecisionEngine,
  explain,
  evaluatePurchase,
  forecast,
  future,
  recommend,
  simulateScenario
} from "./decision-engine";
export {
  DOCUMENTED_INPUTS,
  createFinancialSnapshot,
  createPurchaseCandidate,
  getNormalizedFinancialInputs,
  getSnapshotCurrency
} from "./domain/entities";
export {
  addMoney,
  assertSameCurrency,
  clampMoneyToZero,
  createCurrency,
  createModelVersion,
  createMoney,
  createNonNegativeMoney,
  isGreaterThanMoney,
  isZeroMoney,
  negateMoney,
  subtractMoney,
  sumMoney
} from "./domain/value-objects";
export type {
  AvailableToSpendResult,
  ConfidenceAssessment,
  Currency,
  DecisionConfidence,
  DecisionEngine,
  DailyDecisionInput,
  DailyDecisionOutput,
  ExplanationResult,
  FinancialSnapshot,
  FinancialSnapshotInput,
  ForecastResult,
  FutureResult,
  GoalImpactResult,
  ModelVersion,
  Money,
  NormalizedFinancialInputs,
  PurchaseCandidate,
  PurchaseCandidateInput,
  PurchaseDecision,
  PurchaseEvaluation,
  RecommendationResult,
  RiskLevel,
  RiskAssessment,
  ScenarioSimulation,
  TimelineCheckpoint,
  TimelineCheckpointDirection,
  TimelineCheckpointKey,
  TimelineCheckpointPhase,
  TimelineResult
} from "./types";
